// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2awMl5mFCKu60Q1QTyk3yTEQRKKxQfuY',
    appId: '1:770515273343:web:240d993ee86be23452e14a',
    messagingSenderId: '770515273343',
    projectId: 'd-trade-capital-81ccb',
    authDomain: 'd-trade-capital-81ccb.firebaseapp.com',
    storageBucket: 'd-trade-capital-81ccb.firebasestorage.app',
    measurementId: 'G-80N54381J3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvm3CBIOc0DPAph5aqyjp83jlQ9Ly8b7s',
    appId: '1:770515273343:android:f0ede566f68643cd52e14a',
    messagingSenderId: '770515273343',
    projectId: 'd-trade-capital-81ccb',
    storageBucket: 'd-trade-capital-81ccb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK0SQTWKa_ZC1tfwmdB0UcQ1I1Qio0cio',
    appId: '1:770515273343:ios:a9b4768c3ea04d8a52e14a',
    messagingSenderId: '770515273343',
    projectId: 'd-trade-capital-81ccb',
    storageBucket: 'd-trade-capital-81ccb.firebasestorage.app',
    androidClientId: '770515273343-7hfku02h852vm67kklc16u5t1n2rpceu.apps.googleusercontent.com',
    iosClientId: '770515273343-nv6744eqeoro9604cgorst469milqmce.apps.googleusercontent.com',
    iosBundleId: 'com.example.dtrade',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBK0SQTWKa_ZC1tfwmdB0UcQ1I1Qio0cio',
    appId: '1:770515273343:ios:a9b4768c3ea04d8a52e14a',
    messagingSenderId: '770515273343',
    projectId: 'd-trade-capital-81ccb',
    storageBucket: 'd-trade-capital-81ccb.firebasestorage.app',
    androidClientId: '770515273343-7hfku02h852vm67kklc16u5t1n2rpceu.apps.googleusercontent.com',
    iosClientId: '770515273343-nv6744eqeoro9604cgorst469milqmce.apps.googleusercontent.com',
    iosBundleId: 'com.example.dtrade',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2awMl5mFCKu60Q1QTyk3yTEQRKKxQfuY',
    appId: '1:770515273343:web:708863f191a8890452e14a',
    messagingSenderId: '770515273343',
    projectId: 'd-trade-capital-81ccb',
    authDomain: 'd-trade-capital-81ccb.firebaseapp.com',
    storageBucket: 'd-trade-capital-81ccb.firebasestorage.app',
    measurementId: 'G-TXEHL23CMZ',
  );
}
